export Interface Student {
    firstName: String,
    lastName: String,
    email: String,
    phoneNumber: String,
    userImage: String,
    organizationName: String,
    organizationId: String,
    rollNo: String,
    joinedOn: String,
    address: String,
    linkedinUrl: String,
    githubUrl: String,
    portfolioUrl: String,
}